sequenceDiagram
    participant CLI
    participant debugger
    participant OS

    CLI->>debugger: Attach()
    CLI->>debugger: Launch()
    debugger->>OS: Command()
    debugger->>OS: PtraceAttach()
    debugger->>OS: Wait4()
    debugger->>OS: Kill()
    debugger->>OS: Wait4()
    debugger->>OS: PtraceDetach()
    debugger->>OS: Kill()
    debugger->>OS: Kill()
    debugger->>OS: Wait4()
