flowchart TD
    subgraph main_main["main()"]
        main_main_1["runtime.LockOSThread()"]
        main_main_2{"len(os.Args) &lt; 2"}
        main_main_3["fmt.Fprintln(os.Stderr, #quot;No arguments given#quot;)"]
        main_main_4["os.Exit(1)"]
        main_main_5["proc := attach(os.Args)"]
        main_main_6{"err != nil"}
        main_main_7["fmt.Fprintln(os.Stderr, err)"]
        main_main_8["os.Exit(1)"]
        main_main_9["defer proc.Close()"]
        main_main_10["mainLoop(proc)"]
    end
    subgraph main_attach["attach()"]
        main_attach_1{"len(args) == 3 && args[1] == #quot;-p#quot;"}
        main_attach_2["pid := strconv.Atoi(args[2])"]
        main_attach_3{"err != nil || pid &lt;= 0"}
        main_attach_4(["return nil, fmt.Errorf(#quot;invalid pid#quot;)"])
        main_attach_5(["return debugger.Attach(pid)"])
        main_attach_6(["return debugger.Launch(args[1])"])
    end
    subgraph main_mainLoop["mainLoop()"]
        main_mainLoop_1["rl := readline.New(#quot;(toydbg) #quot;)"]
        main_mainLoop_2{"err != nil"}
        main_mainLoop_3["fmt.Fprintln(os.Stderr, #quot;readline init:#quot;, err)"]
        main_mainLoop_4(["return"])
        main_mainLoop_5["defer rl.Close()"]
        main_mainLoop_6["var lastCmd string"]
        main_mainLoop_7{"loop"}
        main_mainLoop_8["line := rl.Readline()"]
        main_mainLoop_9{"err != nil"}
        main_mainLoop_10(["break"])
        main_mainLoop_11{"line == #quot;#quot;"}
        main_mainLoop_12["line = lastCmd"]
        main_mainLoop_13["lastCmd = line"]
        main_mainLoop_14{"line != #quot;#quot;"}
        main_mainLoop_15{"err != nil"}
        main_mainLoop_16["fmt.Fprintln(os.Stderr, err)"]
    end
    subgraph main_handleCommand["handleCommand()"]
        main_handleCommand_1["args := strings.Fields(line)"]
        main_handleCommand_2["command := args[0]"]
        main_handleCommand_3{"strings.HasPrefix(#quot;continue#quot;, command)"}
        main_handleCommand_4{"err != nil"}
        main_handleCommand_5(["return err"])
        main_handleCommand_6["reason := proc.WaitOnSignal()"]
        main_handleCommand_7{"err != nil"}
        main_handleCommand_8(["return err"])
        main_handleCommand_9["printStopReason(proc, reason)"]
        main_handleCommand_10(["return nil"])
        main_handleCommand_11["fmt.Fprintln(os.Stderr, #quot;Unknown command#quot;)"]
        main_handleCommand_12(["return nil"])
    end
    subgraph main_printStopReason["printStopReason()"]
        main_printStopReason_1["fmt.Printf(#quot;Process %d #quot;, proc.Pid())"]
        main_printStopReason_2{"reason.Reason"}
        main_printStopReason_3["fmt.Printf(#quot;exited with status %d#quot;, reason.Info)"]
        main_printStopReason_4["fmt.Printf(#quot;terminated with signal %s#quot;,  unix.SignalName(unix.Signal(reason.I..."]
        main_printStopReason_5["fmt.Printf(#quot;stopped with signal %s#quot;,  unix.SignalName(unix.Signal(reason.Info)))"]
        main_printStopReason_6["fmt.Println()"]
    end
    subgraph debugger_Error["debugger.Error()"]
        debugger_Error_1(["return e.msg"])
    end
    subgraph debugger_newError["debugger.newError()"]
        debugger_newError_1(["return &Error{msg: msg}"])
    end
    subgraph debugger_newErrorf["debugger.newErrorf()"]
        debugger_newErrorf_1(["return &Error{msg: fmt.Sprintf(format, args...)}"])
    end
    subgraph debugger_newStopReason["debugger.newStopReason()"]
        debugger_newStopReason_1{"switch"}
        debugger_newStopReason_2(["return StopReason{Reason: ProcessExited, Info: uint8(ws.ExitStatus())}"])
        debugger_newStopReason_3(["return StopReason{Reason: ProcessTerminated, Info: uint8(ws.Signal())}"])
        debugger_newStopReason_4(["return StopReason{Reason: ProcessStopped, Info: uint8(ws.StopSignal())}"])
        debugger_newStopReason_5(["return StopReason{Reason: ProcessStopped, Info: 0}"])
    end
    subgraph debugger_Launch["debugger.Launch()"]
        debugger_Launch_1["cmd := exec.Command(program)"]
        debugger_Launch_2["cmd.Stdout = os.Stdout"]
        debugger_Launch_3["cmd.Stderr = os.Stderr"]
        debugger_Launch_4["cmd.SysProcAttr = &syscall.SysProcAttr{  Ptrace: true, }"]
        debugger_Launch_5{"err != nil"}
        debugger_Launch_6(["return nil, newErrorf(#quot;exec failed: %v#quot;, err)"])
        debugger_Launch_7["proc := &Process{  pid:  cmd.Process.Pid,  terminateOnEnd: true,  state:  ProcessStop..."]
        debugger_Launch_8{"err != nil"}
        debugger_Launch_9(["return nil, err"])
        debugger_Launch_10(["return proc, nil"])
    end
    subgraph debugger_Attach["debugger.Attach()"]
        debugger_Attach_1{"pid == 0"}
        debugger_Attach_2(["return nil, newError(#quot;invalid PID#quot;)"])
        debugger_Attach_3{"err != nil"}
        debugger_Attach_4(["return nil, newErrorf(#quot;could not attach: %v#quot;, err)"])
        debugger_Attach_5["proc := &Process{  pid:  pid,  terminateOnEnd: false,  state:  ProcessStopped, }"]
        debugger_Attach_6{"err != nil"}
        debugger_Attach_7(["return nil, err"])
        debugger_Attach_8(["return proc, nil"])
    end
    subgraph debugger_Pid["debugger.Pid()"]
        debugger_Pid_1(["return p.pid"])
    end
    subgraph debugger_State["debugger.State()"]
        debugger_State_1(["return p.state"])
    end
    subgraph debugger_Resume["debugger.Resume()"]
        debugger_Resume_1{"err != nil"}
        debugger_Resume_2(["return newErrorf(#quot;could not resume: %v#quot;, err)"])
        debugger_Resume_3["p.state = ProcessRunning"]
        debugger_Resume_4(["return nil"])
    end
    subgraph debugger_WaitOnSignal["debugger.WaitOnSignal()"]
        debugger_WaitOnSignal_1["var ws syscall.WaitStatus"]
        debugger_WaitOnSignal_2{"err != nil"}
        debugger_WaitOnSignal_3(["return StopReason{}, newErrorf(#quot;waitpid failed: %v#quot;, err)"])
        debugger_WaitOnSignal_4["reason := newStopReason(ws)"]
        debugger_WaitOnSignal_5["p.state = reason.Reason"]
        debugger_WaitOnSignal_6(["return reason, nil"])
    end
    subgraph debugger_Close["debugger.Close()"]
        debugger_Close_1{"p.pid == 0"}
        debugger_Close_2(["return"])
        debugger_Close_3{"p.state == ProcessRunning"}
        debugger_Close_4["_ = syscall.Kill(p.pid, syscall.SIGSTOP)"]
        debugger_Close_5["var ws syscall.WaitStatus"]
        debugger_Close_6["syscall.Wait4(p.pid, &ws, 0, nil)"]
        debugger_Close_7["syscall.PtraceDetach(p.pid)"]
        debugger_Close_8["_ = syscall.Kill(p.pid, syscall.SIGCONT)"]
        debugger_Close_9{"p.terminateOnEnd"}
        debugger_Close_10["_ = syscall.Kill(p.pid, syscall.SIGKILL)"]
        debugger_Close_11["var ws syscall.WaitStatus"]
        debugger_Close_12["syscall.Wait4(p.pid, &ws, 0, nil)"]
    end

    main_main_10 ~~~ main_attach_1
    main_attach_6 ~~~ main_mainLoop_1
    main_mainLoop_16 ~~~ main_handleCommand_1
    main_handleCommand_12 ~~~ main_printStopReason_1
    main_printStopReason_6 ~~~ debugger_Error_1
    debugger_Error_1 ~~~ debugger_newError_1
    debugger_newError_1 ~~~ debugger_newErrorf_1
    debugger_newErrorf_1 ~~~ debugger_newStopReason_1
    debugger_newStopReason_5 ~~~ debugger_Launch_1
    debugger_Launch_10 ~~~ debugger_Attach_1
    debugger_Attach_8 ~~~ debugger_Pid_1
    debugger_Pid_1 ~~~ debugger_State_1
    debugger_State_1 ~~~ debugger_Resume_1
    debugger_Resume_4 ~~~ debugger_WaitOnSignal_1
    debugger_WaitOnSignal_6 ~~~ debugger_Close_1

    main_main_3 --> main_main_4
    main_main_2 -->|"Yes"| main_main_3
    main_main_1 --> main_main_2
    main_main_4 --> main_main_5
    main_main_2 -->|"No"| main_main_5
    main_main_7 --> main_main_8
    main_main_6 -->|"Yes"| main_main_7
    main_main_5 --> main_main_6
    main_main_8 --> main_main_9
    main_main_6 -->|"No"| main_main_9
    main_main_9 --> main_main_10
    main_attach_3 -->|"Yes"| main_attach_4
    main_attach_2 --> main_attach_3
    main_attach_3 -->|"No"| main_attach_5
    main_attach_1 -->|"Yes"| main_attach_2
    main_attach_1 -->|"No"| main_attach_6
    main_mainLoop_3 --> main_mainLoop_4
    main_mainLoop_2 -->|"Yes"| main_mainLoop_3
    main_mainLoop_1 --> main_mainLoop_2
    main_mainLoop_2 -->|"No"| main_mainLoop_5
    main_mainLoop_5 --> main_mainLoop_6
    main_mainLoop_9 -->|"Yes"| main_mainLoop_10
    main_mainLoop_8 --> main_mainLoop_9
    main_mainLoop_11 -->|"Yes"| main_mainLoop_12
    main_mainLoop_11 -->|"No"| main_mainLoop_13
    main_mainLoop_9 -->|"No"| main_mainLoop_11
    main_mainLoop_15 -->|"Yes"| main_mainLoop_16
    main_mainLoop_14 -->|"Yes"| main_mainLoop_15
    main_mainLoop_12 --> main_mainLoop_14
    main_mainLoop_13 --> main_mainLoop_14
    main_mainLoop_7 -->|"Yes"| main_mainLoop_8
    main_mainLoop_16 --> main_mainLoop_7
    main_mainLoop_15 -->|"No"| main_mainLoop_7
    main_mainLoop_14 -->|"No"| main_mainLoop_7
    main_mainLoop_6 --> main_mainLoop_7
    main_handleCommand_1 --> main_handleCommand_2
    main_handleCommand_4 -->|"Yes"| main_handleCommand_5
    main_handleCommand_4 -->|"No"| main_handleCommand_6
    main_handleCommand_7 -->|"Yes"| main_handleCommand_8
    main_handleCommand_6 --> main_handleCommand_7
    main_handleCommand_7 -->|"No"| main_handleCommand_9
    main_handleCommand_9 --> main_handleCommand_10
    main_handleCommand_3 -->|"Yes"| main_handleCommand_4
    main_handleCommand_2 --> main_handleCommand_3
    main_handleCommand_3 -->|"No"| main_handleCommand_11
    main_handleCommand_11 --> main_handleCommand_12
    main_printStopReason_2 -->|"debugger.ProcessExited"| main_printStopReason_3
    main_printStopReason_2 -->|"debugger.ProcessTerminated"| main_printStopReason_4
    main_printStopReason_2 -->|"debugger.ProcessStopped"| main_printStopReason_5
    main_printStopReason_1 --> main_printStopReason_2
    main_printStopReason_3 --> main_printStopReason_6
    main_printStopReason_4 --> main_printStopReason_6
    main_printStopReason_5 --> main_printStopReason_6
    debugger_newStopReason_1 -->|"ws.Exited()"| debugger_newStopReason_2
    debugger_newStopReason_1 -->|"ws.Signaled()"| debugger_newStopReason_3
    debugger_newStopReason_1 -->|"ws.Stopped()"| debugger_newStopReason_4
    debugger_newStopReason_1 -->|"default"| debugger_newStopReason_5
    debugger_Launch_1 --> debugger_Launch_2
    debugger_Launch_2 --> debugger_Launch_3
    debugger_Launch_3 --> debugger_Launch_4
    debugger_Launch_5 -->|"Yes"| debugger_Launch_6
    debugger_Launch_4 --> debugger_Launch_5
    debugger_Launch_5 -->|"No"| debugger_Launch_7
    debugger_Launch_8 -->|"Yes"| debugger_Launch_9
    debugger_Launch_7 --> debugger_Launch_8
    debugger_Launch_8 -->|"No"| debugger_Launch_10
    debugger_Attach_1 -->|"Yes"| debugger_Attach_2
    debugger_Attach_3 -->|"Yes"| debugger_Attach_4
    debugger_Attach_1 -->|"No"| debugger_Attach_3
    debugger_Attach_3 -->|"No"| debugger_Attach_5
    debugger_Attach_6 -->|"Yes"| debugger_Attach_7
    debugger_Attach_5 --> debugger_Attach_6
    debugger_Attach_6 -->|"No"| debugger_Attach_8
    debugger_Resume_1 -->|"Yes"| debugger_Resume_2
    debugger_Resume_1 -->|"No"| debugger_Resume_3
    debugger_Resume_3 --> debugger_Resume_4
    debugger_WaitOnSignal_2 -->|"Yes"| debugger_WaitOnSignal_3
    debugger_WaitOnSignal_1 --> debugger_WaitOnSignal_2
    debugger_WaitOnSignal_2 -->|"No"| debugger_WaitOnSignal_4
    debugger_WaitOnSignal_4 --> debugger_WaitOnSignal_5
    debugger_WaitOnSignal_5 --> debugger_WaitOnSignal_6
    debugger_Close_1 -->|"Yes"| debugger_Close_2
    debugger_Close_4 --> debugger_Close_5
    debugger_Close_5 --> debugger_Close_6
    debugger_Close_3 -->|"Yes"| debugger_Close_4
    debugger_Close_1 -->|"No"| debugger_Close_3
    debugger_Close_6 --> debugger_Close_7
    debugger_Close_3 -->|"No"| debugger_Close_7
    debugger_Close_7 --> debugger_Close_8
    debugger_Close_10 --> debugger_Close_11
    debugger_Close_11 --> debugger_Close_12
    debugger_Close_9 -->|"Yes"| debugger_Close_10
    debugger_Close_8 --> debugger_Close_9
